version: '3'
services:
  my-fastapi-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - '8000:8000'
    depends_on:
      - redis
      - mongodb
    env_file:
     - ./env_file.env
    networks:
      - my-network

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "main.celery_app", "worker", "--loglevel=info"]
    depends_on:
      - my-fastapi-service
    env_file:
     - ./env_file.env
    networks:
      - my-network

  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - my-network

  mongodb:
    image: mongo
    command: mongod --bind_ip_all
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongodb_data:/data/db
    networks:
      - my-network

volumes:
  mongodb_data:

networks:
  my-network:

