version: '3'
services:
  my-fastapi-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis
    ports:
      - '6379:6379'

  mongodb:
    image: mongo
    ports:
      - '27017:27017'

